name: "setup-dxc"
description: "Setup the DirectXShaderCompiler for later usage in the workflow."
author: "Napokue"
inputs:
  tag:
    description: "Optional input that will download a tagged release. When not specified, the latest tag will be downloaded."
    required: false
    default: "latest"
outputs:
  dxc-path:
    description: "Location of the dxc compiler."
runs:
  using: 'node16'
  main: 'dist/index.js'
