name: "build-test"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup-dxc-default
      id: setup-dxc-default
      uses: ./

    - name: test-dxc-default
      run: |
        echo "setup-dxc-default - ${{steps.setup-dxc-default.outputs.dxc-path}}"        
        dxc -help
